import type { Metadata } from "next";
import styles from "../knowledge-base.module.css";
import MermaidDiagram from "../mermaid";

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const metadata: Metadata = {
  title: "Harness Engineering Explained in 20 Mins! | Knowledge Base",
  description: "The most important thing in AI right now has nothing to do with picking the right model \u2014 in fact, the teams shipping the most impressive AI systems w",
};

const TAGS = [`Applied AI`, `Article`, `Aishwarya Srinivasan`];

export default function Page() {
  return (
    <main className={styles.shell}>
      <div className={styles.wrap}>
        <header className={styles.topbar}>
          <a className={styles.brand} href={`${basePath}/knowledge-base/`}>AA / Knowledge Base</a>
          <a className={styles.back} href={`${basePath}/knowledge-base/`}>← All notes</a>
        </header>

        <article className={styles.article}>
          <header className={styles.articleHeader}>
            <span className={styles.eyebrow}>Applied AI · Pipeline article</span>
            <h1>{`Harness Engineering Explained in 20 Mins!`}</h1>
            <p>{`The most important thing in AI right now has nothing to do with picking the right model — in fact, the teams shipping the most impressive AI systems will tell you the model is the easy part. This article, distilled from a video by AI educator and practitioner Aishwarya Srinivasan, explains what harness engineering is, why it is quickly becoming the discipline that separates AI demos from AI products, and how you can start practicing it this week. It is written for software engineers, AI engineers, and technical builders who want their agents to do dependable work for hours at a time rather than produce one-off answers.`}</p>
            <div className={styles.tags}>
              {TAGS.map((tag) => <span className={styles.tag} key={tag}>{tag}</span>)}
            </div>
            <nav className={styles.toc} aria-label="Article sections">
                  <a href={`#the-model-is-the-easy-part`} key="the-model-is-the-easy-part">{`The Model Is the Easy Part`}</a>
                  <a href={`#what-a-harness-is-and-why-a-model-alone-can-t-do-real-work`} key="what-a-harness-is-and-why-a-model-alone-can-t-do-real-work">{`What a Harness Is — and Why a Model Alone Can't Do Real Work`}</a>
                  <a href={`#finding-the-harness-in-the-chatgpt-desktop-app`} key="finding-the-harness-in-the-chatgpt-desktop-app">{`Finding the Harness in the ChatGPT Desktop App`}</a>
                  <a href={`#the-five-components-of-a-production-grade-harness`} key="the-five-components-of-a-production-grade-harness">{`The Five Components of a Production-Grade Harness`}</a>
                  <a href={`#a-five-step-roadmap-to-building-your-own-harness`} key="a-five-step-roadmap-to-building-your-own-harness">{`A Five-Step Roadmap to Building Your Own Harness`}</a>
                  <a href={`#the-model-is-the-commodity-the-harness-is-the-product`} key="the-model-is-the-commodity-the-harness-is-the-product">{`The Model Is the Commodity, the Harness Is the Product`}</a>
                  <a href={`#key-takeaways`} key="key-takeaways">{`Key Takeaways`}</a>
            </nav>
          </header>

            <section className={styles.section} id="the-model-is-the-easy-part">
              <div className={styles.kicker}>Part 01</div>
              <h2>{`The Model Is the Easy Part`}</h2>
              <p>{`Walk into any conversation about building with AI and the question you will hear most often is "which model should we use?" The video argues this is the wrong question. The teams shipping the most impressive AI systems in 2026 will tell you that model selection is the easy part; the hard part, and the part where value is actually created, is everything wrapped around the model.`}</p>
              <p>{`The story that frames the whole video comes from OpenAI. A three-person team started with an empty repository in late August 2025, wrote no code themselves for five months, and ended up with a million lines of production code and 1,500 merged pull requests — every line of it generated by Codex, their coding agent. The detail the team obsessed over, according to the video, was not the prompt and not even the model. It was the harness: the execution environment that made the agent's work possible, reviewable, and safe.`}</p>
              <p>{`The video covers three things. First, what a harness even is, and why a model by itself — no matter how smart — is genuinely handicapped without one. Second, a close look at a product most people use every day, the ChatGPT desktop app, to find the real harness inside its Chat, Work, and Codex experiences; the argument is that once you see it there, you will see it everywhere. Third, the five components of every production-grade harness, plus a step-by-step roadmap for building one yourself.`}</p>
              <p>{`The instructor's background is worth noting as context: Aishwarya Srinivasan spent more than ten years in machine learning and AI, holding data-scientist roles at Microsoft, Google, and IBM, has a master's degree in data science from Columbia University, and led developer relations at the AI startup Fireworks AI before leaving to build her own AI startup. She has also co-founded Gen Academy, an AI skill-building platform focused on what teams actually build in production. She frames harness engineering as building directly on top of two ideas she has covered in earlier videos, loop engineering and context engineering, both linked from the video's description.`}</p>
            </section>

            <section className={styles.section} id="what-a-harness-is-and-why-a-model-alone-can-t-do-real-work">
              <div className={styles.kicker}>Part 02</div>
              <h2>{`What a Harness Is — and Why a Model Alone Can't Do Real Work`}</h2>
              <h3>{`2.1 The Horse and the Harness`}</h3>
              <p>{`The name carries its own explanation. A horse is powerful and fast — but raw power is not useful work. Without a harness, a horse cannot pull a cart or plow a field. The harness is the piece of equipment that converts raw power into directed, useful work. In this analogy the model is the horse, and the harness is everything you build around it: the tools it is allowed to call and the schemas for calling them, the information piped into its context before each run, the checks that run on its outputs, the permission boundaries defining what it can touch, and the logging that records what it actually did.`}</p>
              <h3>{`2.2 What an LLM Can and Cannot Do on Its Own`}</h3>
              <p>{`The reason this matters is that a large language model on its own is a far more limited object than most people realize. Strip away the product around it and what remains is a frozen set of weights that maps input tokens to output tokens — that is the entire interface. Concretely, the model by itself:`}</p>
              <div className={styles.panel}>
                <ul>
                  <li>{`Has no persistent state — everything is gone once the context window closes.`}</li>
                  <li>{`Cannot execute code.`}</li>
                  <li>{`Cannot read a file from disk.`}</li>
                  <li>{`Cannot make an API call.`}</li>
                  <li>{`Cannot even verify a single claim it produces.`}</li>
                </ul>
              </div>
              <p>{`In other words, a bare LLM is a pure function: tokens in, tokens out. Everything you experience as "AI doing useful work" comes from the layer wrapped around that model, and that layer is the harness. Boiled down to a single phrase: the harness is the plumbing around the model.`}</p>
              <h3>{`2.3 Where Harness Engineering Sits Next to Prompt and Context Engineering`}</h3>
              <p>{`Harness engineering is easy to confuse with two terms you already know, and the video places all three precisely:`}</p>
              <div className={styles.panel}>
                <ul>
                  <li><strong>{`Prompt engineering`}</strong>{` optimizes a single exchange: one instruction, one output. It is what you say to the horse.`}</li>
                  <li><strong>{`Context engineering`}</strong>{` manages what the model can see: what gets retrieved and what fits inside the context window. It is what you let the horse see.`}</li>
                  <li><strong>{`Harness engineering`}</strong>{` covers everything else that keeps the horse on the track. Neither of the other two disciplines addresses what happens when an agent runs autonomously for hours and makes hundreds of decisions without any supervision — and that gap is exactly what harness engineering fills.`}</li>
                </ul>
              </div>
              <p>{`Harness engineering is the deliberate design of that execution environment: which tools the agent gets, where its information comes from, how it validates its own work, and when it stops and hands control back to a human.`}</p>
              <h3>{`2.4 A Term That Spread in Weeks`}</h3>
              <p>{`The term itself is very new, and its origin story explains why it spread so fast. In February 2026, Mitchell Hashimoto — co-founder of HashiCorp and creator of Terraform — published a post about his AI adoption journey in which he described a stage he called "engineering the harness." His rule was simple:`}</p>
              <div className={styles.quote}>{`Every time an agent makes a mistake, you engineer the environment so it cannot make that mistake again. It is not a better prompt — it is a permanent fix.`}</div>
              <p>{`Six days later, OpenAI published its write-up of the million lines of Codex-generated code, and Anthropic followed up with a piece on building efficient harnesses for long-running agents. Within weeks, the term was everywhere.`}</p>
              <h3>{`2.5 Better Results Without a Better Model`}</h3>
              <p>{`If you suspect harness engineering is just model quality in disguise, the video points to a clean experiment on exactly this question: one engineer took 15 different LLMs and improved the coding performance of all of them in a single afternoon — without touching a single model. The only thing that changed was the harness. Same weights, better environment, measurably better results. That is the concept in its purest form.`}</p>
              <MermaidDiagram code={"flowchart LR\nsubgraph A1[\"Bare model alone\"]\ndirection TB\na1[\"No persistent state\"]\na2[\"Cannot run code or read files\"]\na3[\"Cannot make API calls\"]\na4[\"Cannot verify a claim\"]\na5[\"Pure function: tokens in, tokens out\"]\na1 --> a2 --> a3 --> a4 --> a5\nend\nsubgraph A2[\"Same model in a harness\"]\ndirection TB\nb1[\"Tools it may call\"]\nb2[\"Context piped in before each run\"]\nb3[\"Checks that run on outputs\"]\nb4[\"Permission boundaries and logging\"]\nb5[\"Directed, useful work\"]\nb1 --> b5\nb2 --> b5\nb3 --> b5\nb4 --> b5\nend\na5 -. \"the difference is the harness\" .-> b5"} caption={`1. The Horse and the Harness: Turning Raw Power into Directed Work — Illustrates Section 2.1, The Horse and the Harness, and Section 2.2, What an LLM Can and Cannot Do on Its Own — the same model alone is a pure function, while the same model in a harness produces directed work.`} />
              <MermaidDiagram code={"flowchart TD\nP[\"Prompt engineering\"] --> P1[\"What you say to the horse\"]\nP1 --> P2[\"One instruction, one output\"]\nC[\"Context engineering\"] --> C1[\"What you let the horse see\"]\nC1 --> C2[\"Retrieval that fits the window\"]\nH[\"Harness engineering\"] --> H1[\"Everything else that keeps the horse on the track\"]\nH1 --> H2[\"Which tools the agent gets\"]\nH1 --> H3[\"Where its information comes from\"]\nH1 --> H4[\"How it validates its own work\"]\nH1 --> H5[\"When it stops and hands back to a human\"]"} caption={`2. Three Disciplines: Prompt, Context, and Harness Engineering — Illustrates Section 2.3, Where Harness Engineering Sits Next to Prompt and Context Engineering — each discipline governs a bigger span, from a single exchange to the whole autonomous run.`} />
            </section>

            <section className={styles.section} id="finding-the-harness-in-the-chatgpt-desktop-app">
              <div className={styles.kicker}>Part 03</div>
              <h2>{`Finding the Harness in the ChatGPT Desktop App`}</h2>
              <p>{`To make the idea concrete, the video takes a product that is sitting on most viewers' desktops and pulls back the layers. In July 2026, OpenAI merged the Codex app and the ChatGPT app into one desktop application containing three experiences: Chat, Work, and Codex. The detail most people missed, the video argues, is that the headline shipment that day was not a new model — it was a harness. The same underlying model family behaves like three completely different products depending on which of these environments it runs in.`}</p>
              <h3>{`3.1 Chat: A Thin Harness for Conversation`}</h3>
              <p>{`The Chat experience feels like just talking to a model, but it isn't. Even here there is a thin harness at work, tuned for the turn-by-turn conversations that happen in a chat window:`}</p>
              <div className={styles.panel}>
                <ul>
                  <li>{`A `}<strong>{`system prompt`}</strong>{` that shapes behavior before you type a single word.`}</li>
                  <li>{`A `}<strong>{`set of tools`}</strong>{` the model can invoke — for example, web search when you ask a question that needs fresh information.`}</li>
                  <li>{`A `}<strong>{`memory system`}</strong>{` that persists facts across your sessions.`}</li>
                  <li>{`A `}<strong>{`sandboxed Python environment`}</strong>{` for any file analysis.`}</li>
                  <li>{`Built-in `}<strong>{`image generation`}</strong>{`.`}</li>
                  <li><strong>{`Safety filters`}</strong>{` running on inputs and outputs.`}</li>
                </ul>
              </div>
              <h3>{`3.2 Work: A Heavier Harness for Getting Things Done`}</h3>
              <p>{`Work mode is the same application with a toggle flipped, but now you are talking to an agent, not a model. It gathers context from your files and connected applications, decomposes a goal into steps, and runs for hours to produce finished documents, spreadsheets, and presentations. The model's raw capability did not change — the harness got heavier. Work adds:`}</p>
              <div className={styles.panel}>
                <ul>
                  <li>{`A `}<strong>{`planning loop`}</strong>{`.`}</li>
                  <li><strong>{`Connectors`}</strong>{` into your actual tools and the ability to take actions across them.`}</li>
                  <li><strong>{`Approval checkpoints`}</strong>{` where the agent pauses before doing anything consequential.`}</li>
                  <li><strong>{`Scheduled tasks`}</strong>{` that keep running even after you walk away.`}</li>
                </ul>
              </div>
              <p>{`Those approval checkpoints deserve attention: they are a guardrail, a harness component, placed there by an engineer who decided the agent should stop at exactly that point rather than guess. The video flags this as a detail to remember — it returns when the five components are laid out.`}</p>
              <h3>{`3.3 Codex: The Heaviest Harness of All`}</h3>
              <p>{`Codex mode is the heaviest harness of the three and, for technical viewers, the most instructive. It gets a sandboxed execution environment or scoped access to a local folder, where you explicitly grant what it can touch. Before it writes a single line, it reads the `}<code>{`AGENTS.md`}</code>{` file at the root of your repository — your team's accumulated instructions and conventions. It has a terminal, so it can actually run your build and your test suite and observe its own failures. It produces diffs for your review, inline, and it can actually review pull requests. Every capability is scoped, logged, and wrapped in a feedback loop.`}</p>
              <p>{`That, the video says, is exactly why the same intelligence that makes small talk in the Chat tab can autonomously refactor a codebase in the Codex tab: the weights of the model did not change — the environment and the harness did. So when someone asks "which AI is the best?", the honest answer is that they are asking about the horse when they should be asking about the harness.`}</p>
              <MermaidDiagram code={"flowchart TD\nM[\"Same model family \u2014 one desktop app\"]\nM --> c1\nM --> w1\nM --> x1\nsubgraph S1[\"Chat \u2014 thin harness\"]\ndirection TB\nc1[\"System prompt shapes behavior\"]\nc2[\"Web search and a few tools\"]\nc3[\"Memory across sessions\"]\nc4[\"Sandboxed Python and image generation\"]\nc1 --> c2 --> c3 --> c4\nend\nsubgraph S2[\"Work \u2014 heavier harness\"]\ndirection TB\nw1[\"Planning loop\"]\nw2[\"Connectors that take actions\"]\nw3[\"Approval checkpoints\"]\nw4[\"Scheduled tasks\"]\nw1 --> w2 --> w3 --> w4\nend\nsubgraph S3[\"Codex \u2014 heaviest harness\"]\ndirection TB\nx1[\"Scoped access to a folder\"]\nx2[\"Reads AGENTS.md conventions\"]\nx3[\"Terminal for builds and tests\"]\nx4[\"Inline diffs and PR review\"]\nx1 --> x2 --> x3 --> x4\nend"} caption={`3. Chat, Work, and Codex: Three Harnesses in One App — Illustrates Section 3, Finding the Harness in the ChatGPT Desktop App — the same model family behaves like three different products as the harness gets heavier.`} />
            </section>

            <section className={styles.section} id="the-five-components-of-a-production-grade-harness">
              <div className={styles.kicker}>Part 04</div>
              <h2>{`The Five Components of a Production-Grade Harness`}</h2>
              <p>{`Whenever you use Chat, Work, or Codex — or Claude Code on the Anthropic side — you are a harness `}<em>{`customer`}</em>{`: someone else engineered that environment for you. Harness engineering is learning to build that layer yourself, for your own agents and your own workflows. Which raises the obvious question: what is that layer actually made of?`}</p>
              <p>{`Almost every production system uses some combination of five components, and you will feel it even if one of them is missing.`}</p>
              <h3>{`4.1 The System of Record`}</h3>
              <p>{`The first component is instruction files — the system of record for how an agent should work. If you have used Claude Code or Cursor, you have seen `}<code>{`CLAUDE.md`}</code>{` or `}<code>{`AGENTS.md`}</code>{` in the root of a project: a plain Markdown file the agent reads before working, containing the project structure, the conventions, the build commands, and the decisions your team has already made.`}</p>
              <p>{`The OpenAI team hit this trap directly. Without written answers to questions like "what abstractions should I use?", the agent guesses — and guesses wrong, repeatedly. Their conclusion: if knowledge lives in Slack threads and Google Docs instead of the repository, the agents cannot really see it, so it might as well not exist. Everything the agent needs has to live where the agent works.`}</p>
              <h3>{`4.2 Tools`}</h3>
              <p>{`The second component is tools: what can your agent actually do? Run shell commands, edit files, search the web, query a database, and so on. Most people fall into one of two extremes — access to everything, which makes behavior unpredictable, or access to almost nothing, which makes the agent talk but not really act. Good harness design sits in between: a small, deliberate set of tools, where you can justify for each one why the agent needs it.`}</p>
              <h3>{`4.3 Feedback Loops and Verification`}</h3>
              <p>{`The third component is the one most people skip — and the video is explicit that you should not. An agent needs a way to check its own work without asking you. In code, that machinery already exists: a linter, a type checker, or a real test suite that runs automatically after every change, so the agent observes its own failures and fixes them before you even look at the output.`}</p>
              <h3>{`4.4 Guardrails and Permissions`}</h3>
              <p>{`The fourth component answers a different question: what is the agent explicitly `}<em>{`not`}</em>{` allowed to do? Which parts are read-only? Which commands require approval? At what point does it stop and ask, instead of guessing? The approval prompts you see in ChatGPT's Work experience are this exact component, designed at OpenAI scale. Every serious agent tool exposes these settings — and most people never touch them. You need to set them deliberately.`}</p>
              <h3>{`4.5 Observability and Memory`}</h3>
              <p>{`The fifth component is observability and memory. Observability is a record of everything the agent did: every tool call, every decision, every error. Memory carries useful state across different sessions, because the model itself cannot carry anything. When a run goes wrong — and it will — the record is the only way to reconstruct what happened, instead of guessing.`}</p>
              <MermaidDiagram code={"flowchart TD\nH[\"Production-grade harness\"] --> C1[\"1. System of record\"]\nH --> C2[\"2. Tools\"]\nH --> C3[\"3. Feedback loops and verification\"]\nH --> C4[\"4. Guardrails and permissions\"]\nH --> C5[\"5. Observability and memory\"]\nC1 --> E1[\"AGENTS.md and CLAUDE.md\"]\nC2 --> E2[\"A small, deliberate set\"]\nC3 --> E3[\"Linters, type checks, test suites\"]\nC4 --> E4[\"Read-only scopes and approval gates\"]\nC5 --> E5[\"Logs and memory across sessions\"]"} caption={`4. The Five Components of a Production-Grade Harness — Illustrates Section 4, The Five Components of a Production-Grade Harness — the layer you build around the model, and the concrete form each component takes.`} />
              <MermaidDiagram code={"stateDiagram-v2\n[*] --> Plan: goal arrives\nPlan --> Act: break it into steps\nAct --> Verify: the agent takes an action\nVerify --> Fix: a check fails\nFix --> Verify: it corrects its own work\nVerify --> Handoff: every check passes\nHandoff --> [*]"} caption={`5. The Verification Loop: An Agent That Checks Its Own Work — Illustrates Section 4.3, Feedback Loops and Verification, and Step 2 in Section 5.2, Build a Verification Loop — checks run automatically so the agent discovers its own mistakes before you do.`} />
            </section>

            <section className={styles.section} id="a-five-step-roadmap-to-building-your-own-harness">
              <div className={styles.kicker}>Part 05</div>
              <h2>{`A Five-Step Roadmap to Building Your Own Harness`}</h2>
              <p>{`Theory is useful, but the video closes with the practitioner's question: how do you actually go build one? The roadmap below is meant to be worked through week by week.`}</p>
              <h3>{`5.1 Step 1 — Create Your System of Record This Week`}</h3>
              <p>{`The instruction file already has a home in every tool you might use. In Codex — whether the CLI or the Codex tab inside the ChatGPT desktop app — the file is `}<code>{`AGENTS.md`}</code>{` at your repository's root, and Codex picks it up automatically. In Claude Code it is called `}<code>{`CLAUDE.md`}</code>{`, and you can run the `}<code>{`/init`}</code>{` command to have it generate a starting point for you. Cursor also reads `}<code>{`AGENTS.md`}</code>{`.`}</p>
              <p>{`Whatever tool you are in, write down four things: how the project is structured, how to run it, how to test it, and your top five conventions. Keep it under a page. Then adopt Hashimoto's discipline as a personal rule: when the agent makes the same mistake twice, do not explain the fix in the chat — write it into the file permanently. Hashimoto has said that almost every line in the `}<code>{`AGENTS.md`}</code>{` of his own project came from a past agent failure. Once a rule is in the file, that mistake essentially never recurs. That single habit is harness engineering in miniature — and it compounds.`}</p>
              <h3>{`5.2 Step 2 — Build a Verification Loop`}</h3>
              <p>{`Learn to build your own verification loop. In Python, that means a linter like Ruff plus a handful of real tests; the same idea applies in JavaScript with the standard tooling. Configure your agent to run those checks after every single change — in Claude Code you can wire this up with hooks so the checks fire automatically, instead of relying on the agent to remember.`}</p>
              <p>{`If your agent is not writing code, the principle still holds: define what correct output looks like, write a script or checklist that validates it, and make that check part of every single run. The goal is simple: agents should discover their own mistakes before you do.`}</p>
              <h3>{`5.3 Step 3 — Choose Tools Deliberately`}</h3>
              <p>{`Before building anything custom, spend a week working inside one serious existing harness — either Claude Code or Codex — and actually study how it behaves. When does it ask for permission? How does it use your instruction file? How does it run your tests? You will learn more from watching a well-built harness than from any YouTube tutorial — including, as the video puts it, this one.`}</p>
              <p>{`Then extend outward: connect your agent to one real system you use every day, using MCP (the Model Context Protocol, covered in a separate video by the same instructor). For every single tool connection, ask the harness question: `}<em>{`What is the worst thing the agent could do with this access — and how have I done anything to prevent it?`}</em></p>
              <h3>{`5.4 Step 4 — Read Your Failures`}</h3>
              <p>{`Turn on whatever logging your agent tool provides. When a run goes wrong, read through what the agent did, step by step. It might sound tedious, but it is the single highest-leverage habit in the entire video. Every failed run tells you exactly which piece of the harness to build next: is it a missing instruction, a missing check, or a tool the agent should never have had access to? As the video puts it, your harness roadmap is written in your failure logs.`}</p>
              <h3>{`5.5 Step 5 — Build One Complete Harness for One Narrow Workflow`}</h3>
              <p>{`This is the graduation project. Pick one repetitive, well-defined task you will be doing every single week, and build the full loop around it: an instruction file, a small set of tools, automated verification, a clear set of permissions, and logging. It should be one workflow, end to end, running reliably without you babysitting it. Do that once, and you will understand the discipline at a level no blog post can ever teach you.`}</p>
              <MermaidDiagram code={"stateDiagram-v2\n[*] --> Plan: goal arrives\nPlan --> Act: break it into steps\nAct --> Verify: the agent takes an action\nVerify --> Fix: a check fails\nFix --> Verify: it corrects its own work\nVerify --> Handoff: every check passes\nHandoff --> [*]"} caption={`5. The Verification Loop: An Agent That Checks Its Own Work — Illustrates Section 4.3, Feedback Loops and Verification, and Step 2 in Section 5.2, Build a Verification Loop — checks run automatically so the agent discovers its own mistakes before you do.`} />
              <MermaidDiagram code={"flowchart TD\nS1[\"Step 1 \u2014 write the system of record this week\"] --> S2[\"Step 2 \u2014 build a verification loop\"]\nS2 --> S3[\"Step 3 \u2014 choose tools deliberately\"]\nS3 --> S4[\"Step 4 \u2014 read your failures\"]\nS4 --> S5[\"Step 5 \u2014 one harness for one narrow workflow\"]\nS5 --> O[\"Runs end to end without babysitting\"]\nS4 -. \"each failure names the next fix\" .-> S1"} caption={`6. The Five-Step Roadmap: From One File to One Workflow — Illustrates Section 5, A Five-Step Roadmap to Building Your Own Harness — write one file this week, then add verification, tools, failure reading, and finally one narrow workflow running end to end.`} />
            </section>

            <section className={styles.section} id="the-model-is-the-commodity-the-harness-is-the-product">
              <div className={styles.kicker}>Part 06</div>
              <h2>{`The Model Is the Commodity, the Harness Is the Product`}</h2>
              <p>{`The video's closing argument looks forward. In 2026 and 2027, the model is increasingly becoming the commodity in the stack: everyone has access to roughly the same frontier intelligence, especially with open-source models — the video name-checks the latest open releases such as Kimi K3 as worth trying out. What you actually compete on is the environment you build around the model: the instruction files, the feedback loops, the permissions, the observability. That is harness engineering, and it is increasingly becoming the standard for most companies.`}</p>
              <div className={styles.quote}>{`You don't get a better agent by finding a better model. You get a better agent by building it with a better harness.`}</div>
              <p>{`At the end of the day, this is all software engineering — engineering and plumbing the thing around the model. For viewers who want to go further, the video points to its own follow-ups: earlier explainers on loop engineering and context engineering, a free live masterclass on building agentic loops and harnesses, and the six-week "Mastering Agentic AI" program at Gen Academy, which offers both no-code/low-code and code-heavy project tracks and runs cohorts with educational partners including NVIDIA, OpenAI, Pinecone, Replicate, and ElevenLabs.`}</p>
            </section>

            <section className={styles.section} id="key-takeaways">
              <div className={styles.kicker}>Summary</div>
              <h2>Key Takeaways</h2>
              <div className={styles.checklist}>
              <div className={styles.check}>{`A bare LLM is a pure function — tokens in, tokens out. It has no memory, cannot run code, read files, make API calls, or verify its own claims; everything useful comes from the layer around it, and that layer is the harness.`}</div>
              <div className={styles.check}>{`Harness engineering sits on top of prompt engineering (what you say to the horse) and context engineering (what you let the horse see): it governs long-running, autonomous runs where an agent makes hundreds of unsupervised decisions.`}</div>
              <div className={styles.check}>{`The term went mainstream in weeks after Mitchell Hashimoto's February 2026 post, OpenAI's million-lines-of-Codex write-up, and Anthropic's piece on harnesses for long-running agents — and an experiment improving all 15 tested LLMs without touching their weights shows the harness, not the model, drives measurable gains.`}</div>
              <div className={styles.check}>{`The ChatGPT desktop app demonstrates the idea: Chat runs on a thin harness, Work on a heavier one with planning loops, connectors, approval checkpoints, and scheduled tasks, and Codex on the heaviest — sandboxed execution, `}<code>{`AGENTS.md`}</code>{`, a terminal for running builds and tests, and inline diffs.`}</div>
              <div className={styles.check}>{`Five components make up a production-grade harness: system of record (instruction files), tools, feedback loops and verification, guardrails and permissions, and observability and memory.`}</div>
              <div className={styles.check}>{`Start by writing a short `}<code>{`AGENTS.md`}</code>{`/`}<code>{`CLAUDE.md`}</code>{` this week, and adopt Hashimoto's rule: never explain the same mistake twice in chat — write the fix into the file permanently.`}</div>
              <div className={styles.check}>{`Wire automated checks (linters, tests, hooks) into every run, spend a week studying a serious existing harness before building your own, connect tools via MCP one at a time, and treat failure logs as your roadmap.`}</div>
              <div className={styles.check}>{`As model access commoditizes, competition shifts to the environment: instruction files, feedback loops, permissions, and observability.`}</div>
              </div>
            </section>

          <footer className={styles.footer}>
            Source: <a href={`https://www.youtube.com/watch?v=bsmUh5bTNZ4`}>{`Harness Engineering Explained in 20 Mins!`}</a> by <a href={`https://www.youtube.com/@aishwaryasrinivasan`}>{`Aishwarya Srinivasan`}</a> · metadata fetched {`2026-09-02T10:58:03.084913+00:00`} Built by the <a href={`${basePath}/knowledge-base/`}>Knowledge Base</a> YouTube → article pipeline.
          </footer>
        </article>
      </div>
    </main>
  );
}

